SecondYear/WAD2/currentWeb/freshmen_world/WOF/urls.py
from django.urls import path
from WOF import views

app_name = 'WOF'

urlpatterns = [
	path('', views.index, name='index'),
	path('base/', views.base, name='base'),
	path('login/', views.user_login, name='user_login'),
	path('register/', views.user_register, name='user_register'),
	path('course_selector/', views.selector, name='selector'),
	path('taskmanager/', views.task_manager, name='task_manager'),
	path('logout/', views.user_logout, name='logout'),
]

SecondYear/WAD2/currentWeb/freshmen_world/freshmen_world/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from WOF import views


urlpatterns = [
    path('', views.index, name='index'),
    path('WOF/', include('WOF.urls')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

SecondYear/WAD2/currentWeb/freshmen_world/WOF/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User

# Create your models here.
class StudentUserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    email = models.CharField(max_length=60, unique = False, default="")
    university = models.CharField(max_length=80, unique = False, default="")
    degree = models.CharField(max_length=30, unique = False, default="")
    level = models.IntegerField(default=0)

    class Meta:
        verbose_name_plural = 'Student Users'

    def __str__(self):
        return self.user.username


class Task(models.Model):
    name=models.CharField(max_length=40, unique = False)
    completed= models.BooleanField(default=False);
    dueDate= models.DateTimeField(
        verbose_name=("Creation date"), auto_now_add=True, null=True
    )
    timePlanned= models.TimeField(auto_now=False, auto_now_add=False);

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)


    class Meta:
        verbose_name_plural = 'Tasks'

    def __str__(self):
        return self.name


class AdminUser(models.Model):
    firstName = models.CharField(max_length = 40,unique = False)
    secondName = models.CharField(max_length = 40,unique = False)
    password = models.CharField(max_length = 20,unique = False)
    email = models.CharField(max_length = 60,unique = True)
    university = models.CharField(max_length = 80,unique = False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)
    
    class Meta:
        verbose_name_plural = 'Admin Users'
        
    def __str__(self):
        return self.email
        

class Course(models.Model):
    name = models.CharField(max_length = 80,unique = True)
    level = models.IntegerField(unique = False)
    credits = models.IntegerField(unique = False)
    courseConvener = models.CharField(max_length = 90, unique = False)
    courseNumber = models.CharField(max_length = 30, unique = False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)    
    
    class Meta:
        verbose_name_plural = 'Courses'
        
    def __str__(self):
        return self.name
        
           
class University(models.Model):
    name = models.CharField(max_length = 80,unique = False)
    Location = models.CharField(max_length = 80, unique = False)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)    
    
    class Meta:
        verbose_name_plural = 'Universites'
        
    def __str__(self):
        return self.name

SecondYear/WAD2/currentWeb/freshmen_world/WOF/forms.py
from django import forms
from WOF.models import StudentUserProfile
from django.contrib.auth.models import User

class StudentUserForm(forms.ModelForm):
	password = forms.CharField(widget=forms.PasswordInput())

	class Meta:
		model = User
		fields = ('username', 'password',)

class StudentUserProfileForm(forms.ModelForm):
	class Meta:
		model = StudentUserProfile
		fields = ('email', 'university', 'degree', 'level', )

SecondYear/WAD2/currentWeb/freshmen_world/WOF/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from WOF.forms import StudentUserForm, StudentUserProfileForm

def index(request):
	context_dict = {}
	response = render(request, 'WOF/index.html', context=context_dict)
	return response

def base(request):
	return render(request, 'WOF/base.html', context={})

def user_login(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(username=username, password=password)

		if user:
			if user.is_active:
				login(request, user)
				return redirect(reverse('WOF:index'))
			else:
				return HttpResponse("Account disabled")
		else:
			print(f"Invalid login details supplied: {username}, {password}")
			return HttpResponse("Invalid login details supplied")
	else:
		return render(request, 'WOF/user_login.html')
	return response

def user_register(request):
	registered = False

	if request.method == "POST":
		student_user_form = StudentUserForm(request.POST)

		if student_user_form.is_valid():
			student_user = student_user_form.save()
			student_user.set_password(student_user.password)
			student_user.save()

			registered = True
		else:
			print(student_user_form.errors)
	else:
		student_user_form = StudentUserForm()
	return render(request, 'WOF/register2.html', context={'student_user_form': student_user_form, 'registered': registered})

@login_required
def user_logout(request):
	logout(request)
	return redirect(reverse('WOF:index'))

def selector(request):
	context_dict = {}
	response = render(request, 'WOF/selecting.html', context=context_dict)
	return response

def task_manager(request):
	context_dict = {}
	response = render(request, 'WOF/taskmanager.html', context=context_dict)
	return response

SecondYear/WAD2/currentWeb/freshmen_world/templates/WOF/base.html
<!DOCTYPE html>
{% load staticfiles %}

<html>

    <head lang="en">
        <meta charset="UTF-8" />
        <title>
            Freshmen World - 
            {% block title_block %}
                Still making progress!
            {% endblock %} 
        </title>
        <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
        <script type="text/javascript" src="{% static 'js/base.js' %}"></script>
        <link rel="stylesheet" href="{% static 'css/reset.css' %}">
        <link rel="stylesheet" href="{% static 'css/base.css' %}">
    </head>

    <body>
        <div>
            {% block top_bar_block %}
                {% if user.is_authenticated %} 
                    <div class="top_bar_login">
                        <div class="logo"><img src="{% static 'images/logo.png' %}" alt="Logo"></div>
                        <div class="bar_link"><a href="{% url 'WOF:selector' %}">Course Selector</a></div>
                        <div class="bar_link"><a href="{% url 'WOF:task_manager' %}">Task Manager</a></div>
                        <div class="bar_link"><a href="{% url 'WOF:logout' %}">Logout</a></div>
                    </div>
                {% else %}
                    <div class="top_bar_nonlogin"> 
                        <div class="logo"><img src="{% static 'images/logo.png' %}" alt="Logo"></div>
                        <div class="bar_link"><a href="{% url 'WOF:selector' %}">Course Selector</a></div>
                        <div class="bar_link"><a href="{% url 'WOF:task_manager' %}">Task Manager</a></div>
                        <div class="bar_link"><a href="{% url 'WOF:user_login' %}">Login</a></div>
                        <div class="bar_link"><a href="{% url 'WOF:user_register' %}">Register</a></div>
                    </div>
                 {% endif %}
            {% endblock %}
            <div class="body_block">
                {% block body_block %}
                {% endblock %}
            </div>
            {% block bottom_bar_block %}
            <div class="bottom_bar">
                <hr id="bottom_bar_line">
                <div class="message">
                    <div class="name">Message</div>
                </div>
                <div class="details">
                    <div class="detail_left">
                        <ul>
                            <li>About us</li>
                            <li>Terms</li>
                            <li>Help Documents</li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        {% endblock %}  
    </body>
</html>

SecondYear/WAD2/currentWeb/freshmen_world/templates/WOF/index.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Index page!
{% endblock %}


{% block body_block %}
    <link rel="stylesheet" href="{% static 'css/index.css' %}"> 

    <div class="mainbody">
        <div class="mainbody_left">
            <div class="weather">

            </div>
            <div class="content_name">
                University event
            </div>
            <div class="content">
                <div class="content_show">
                    <p>Some content goes here</p>
                </div>
            </div>
        </div>

        <div class="mainbody_center">
            <div class="schoolimg">

            </div>
            <div class="searchbar">
                <input type="text" placeholder="Type here...">
                <button type="submit"><i class="fa fa-search"></i></button>
            </div>
            <div class="info_of_uni">
                <div class="info_of_uni_show">
                    <p>Words about university will go here!</p>
                </div>
            </div>
        </div>
    
        <div class="mainbody_right">
            <div class="helper_title">
                Who can help you in University
            </div>
            <div class="helper">
                <div class="helper_show">
                    <p>Words will go here</p>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

SecondYear/WAD2/currentWeb/freshmen_world/templates/WOF/register2.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
	Second register page
{% endblock %}

{% block body_block %}
{% if registered %}
WOF says: <strong>thank you for registering!</strong>
<a href="{% url 'WOF:index' %}">Return to the homepage.</a><br />
{% else %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}"/>
	<form id="student_user_form" method="post" action="{% url 'WOF:user_register' %}" enctype="multipart/form-data">

		{% csrf_token %}
		{{ student_user_form.as_p }}

		<input type="submit" name="submit" value="Register" />
	</form>
{% endif %}
{% endblock%}

SecondYear/WAD2/currentWeb/freshmen_world/templates/WOF/selecting.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/selecting.css">
    <link rel="stylesheet" href="../css/all.css">
    <link rel="stylesheet" href="../css/reset.css">
    <title>Course Selecting</title>
</head>
<body>
    
</body>
</html>

SecondYear/WAD2/currentWeb/freshmen_world/templates/WOF/taskmanager.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="../css/taskmanager.css">
    <link rel="stylesheet" href="../css/all.css">
    <link rel="stylesheet" href="../css/reset.css">
    <title>Task Manager</title>
</head>

<body>
    <div class="main_body">

        <div class="first_part">
            <div class="course">Courses</div>
            <div class="month">Date</div>
        </div>

        <div class="title">
            <div id="last_month">Last Month</div>
            <div id="year"></div>
            <div id="month"></div>
            <div id="next_month">Next Month</div>
        </div>

        <div class="week">
            <div id="Sunday">Sunday</div>
            <div id="Monday">Monday</div>
            <div id="Tuesday">Tuesday</div>
            <div id="Wednesday">Wednesday</div>
            <div id="Thursday">Thursday</div>
            <div id="Friday">Friday</div>
            <div id="Saturday">Saturday</div>
        </div>

        <div class="third_part">
            <div class="perline">
                <div class="date">
                    <div class="day" id="1"></div>
                    <div class="message">fad</div>
                </div>
                <div class="date">
                    <div class="day" id="2"></div>
                    <div class="message">hafgf</div>
                </div>
                <div class="date">
                    <div class="day" id="3"></div>
                    <div class="message">rqew</div>
                </div>
                <div class="date">
                    <div class="day" id="4"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="5"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="6"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="7"></div>
                    <div class="message"></div>
                </div>
            </div>
            <div class="perline">
                <div class="date">
                    <div class="day" id="8"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="9"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="10"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="11"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="12"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="13"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="14"></div>
                    <div class="message"></div>
                </div>
            </div>
            <div class="perline">
                <div class="date">
                    <div class="day" id="15"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="16"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="17"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="18"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="19"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="20"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="21"></div>
                    <div class="message"></div>
                </div>
            </div>
            <div class="perline">
                <div class="date">
                    <div class="day" id="22"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="23"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="24"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="25"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="26"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="27"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="28"></div>
                    <div class="message"></div>
                </div>
            </div>
            <div class="perline">
                <div class="date">
                    <div class="day" id="29"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="30"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="31"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="32"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="33"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="34"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="35"></div>
                    <div class="message"></div>
                </div>
            </div>
            <div class="perline">
                <div class="date">
                    <div class="day" id="36"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="37"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="38"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="39"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="40"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="41"></div>
                    <div class="message"></div>
                </div>
                <div class="date">
                    <div class="day" id="42"></div>
                    <div class="message"></div>
                </div>
            </div>
        </div>
    </div>

    <script>
        let date = new Date();
        console.log(date.getMonth())
        update();
        function update() {
            let year = date.getFullYear();
            let month = date.getMonth();
            let day = date.getDate();
            let firstDay = new Date(year, month, 1).getDay();
            let monthLength = new Date(year, month, 0).getDate();


            let array = ["January", "Febuary", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"];

            document.getElementById("year").innerHTML = year;
            document.getElementById("month").innerHTML = array[month];
            
            let j = firstDay;
            let z = 1;
            for(let i = 1; i <= monthLength ;i++){
                document.getElementById(j+i).innerHTML = z;
                if(document.getElementById(j).innerHTML == day){
                    document.getElementById(j).style.color = "red";
                }else{
                    document.getElementById(j).style.color = "black";
                }
                z++;
            }

        }

        document.getElementById("last_month").onclick = function(){
            date.setMonth(date.getMonth()-1);
            update();
        };
        document.getElementById("next_month").onclick = function(){
            date.setMonth(date.getMonth()+1);
            update();
        };
    </script>
</body>

</html>

SecondYear/WAD2/currentWeb/freshmen_world/templates/WOF/user_login.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Login
{% endblock %}

{% block body_block %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}"/>
    <h1> Login page </h1>
    <form id="login_form" method="post" action="{% url 'WOF:user_login' %}">
        {% csrf_token %}
        Username: <input type="text" name="username" value="" size="40" />
        <br />
        Password: <input type="password" name="password" value="" size="20" />
        <br />
        <input type="submit" value="submit" />
    </form>
{% endblock %}

SecondYear/WAD2/currentWeb/freshmen_world/templates/WOF/user_register.html
{% extends 'WOF/base.html' %}
{% load staticfiles %}

{% block title_block %}
    Register page!
{% endblock %}

{% block body_block %}
	<link rel="stylesheet" type="text/css" href="{% static 'css/register.css' %}"/>
	<div class="body_block">
		<div class="loginInterface">
			<div class="loginBlock">
				<form method="post" action="{% url 'WOF:user_register' %}" enctype="multipart/form-data">
					{% csrf_token %}
					<div class="loginBlock_text">Register<span><a href="{% url 'WOF:user_login' %}">login</a></span></div>
					<div class="loginBlock_input">
							<input type="text" placeholder="Name" name="name"> <br />
							<input type="password" placeholder="Password" name="password"> <br />
							<input type="email" placeholder="Email" name="email"> <br />
					</div>
					
					<div class="loginBlock_button">
						<button class="btn btn-block">submit</button>
					</div>
				</form>
			</div>
			<div id="foot">
				<p>All rights reserved</p>
			</div>
		</div>
	</div>
{% endblock %}